version: 2

models:
  - name: stg_clientes
    enabled: true
    materialized: table
    columns:
      - name: id_cliente
        tests:
          - unique
          - not_null

  - name: stg_pagamentos
    columns:
      - name: id_pedido
        tests:
          - unique
          - not_null

  - name: stg_pedidos
    columns:
      - name: id_pagamento
        tests:
          - unique
          - not_null
      - name: metodo_pagamento
        tests:
          - accepted_values:
              values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']
