services:

  dbpg: # Nome do nosso servico de banco de dados PostgreSQL
    image: postgres:13-alpine # Usa uma imagem oficial do PostgreSQL (versao Alpine e menor)
    environment: # Variaveis de ambiente para configurar o PostgreSQL
      POSTGRES_DB: ${DB_NAME:-5432}
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persiste os dados do PostgreSQL
    ports:
      - "5432:5432" # Mapeia a porta 5432 do container para a 5432 do host (opcional para este exercicio, mas util para acesso externo)
    networks:
      - app-network

  dbt:
    build: ./dbt
    depends_on:
      - dbpg
    environment:
      - DB_HOST=${DB_HOST:-mydatabase}
      - DB_PORT=${DB_PORT:-mydatabase}
      - DB_NAME=${DB_NAME:-mydatabase}
      - DB_USER=${DB_USER:-user}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_SCHEMA=${DB_SCHEMA:-public}
    ports: 
      - "8080:8080"
    networks:
      - app-network
    command: tail -f /dev/null


volumes:
  postgres_data: # Define um volume nomeado para persistencia dos dados do DB

networks:
  app-network: # Define uma rede customizada do tipo bridge
    driver: bridge 
